### ISSUE TITLE
npm start error: "sh: 1: node: not found"

### ISSUE THREAD

**Issue by Oblynx** [htm-community/htm-school-viz#18]
Hi,
I installed the nupic-history-server and have it running on port 8000 with the command "redis-server --port 8000". Then I attempted to start the htm-school-viz with "npm start 8080". The firewall is disabled and I installed the dependencies with **"npm install --user"**.
The npm error log follows:

[npm-debug.log.txt](https://github.com/htm-community/htm-school-viz/files/872638/npm-debug.log.txt)

**Comment by rhyolight** [comment]
I am sorry, but this is a low-priority repository for me. If you have a specific question, I'll try to answer it, but I am not fixing bugs unless I happen to run into them. This repo is just a tool I use to create my educational videos. I need to spend most of my time on those.

**Comment by rikkertkoppes** [comment]
It does not seem to be a repo issue. From your log:

	13 verbose stack Error: htm-school-viz@1.0.0 start: `node index.js "8080"`
	13 verbose stack spawn ENOENT
	13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)

Did you investigate anything? Can you manually find spawn? Did you try updating / reinstalling node? Are your folder permissions all ok?

**Comment by rhyolight** [comment]
Also, PRs are welcome.

**Comment by Oblynx** [comment]
Thanks for the replies!
@rikkertkoppes  I know nothing about how npm works, so sorry if this is a premature issue. Folder permissions might actually be the issue here, because I installed npm dependencies for the user and not systemwide. Thanks for the suggestions!
@rhyolight I understand and thanks for providing this code. If this were really a bug, I simply thought I might as well ask about it.

**Comment by rhyolight** [comment]
No worries @Oblynx! Thanks for posting the issue.

**Comment by Oblynx** [comment]
Actually, I solved this by installing the "nodejs-legacy" package (ubuntu).
