### ISSUE TITLE
Fails to run for Ep. 7+

### ISSUE THREAD

**Issue by breznak** [htm-community/htm-school-viz#19]
Related to #9  - but not the same issue. 

- I fixed redis to run on expected port 8000 https://github.com/htm-community/nupic-history-server/issues/9 
- there I also had to update the dependencies 
 - you've used some local build `0.5.7.dev0 and 0.4.13.dev0`, which are not available
 - tested with both: stable (`0.5.7 and 0.4.13`), and latest (just nupic, nupic.bindings in requirements) 

And I get the same error: 
```
(schools) mmm@mmm-U2442:/mnt/store/devel/HTM/htm_schools/htm-school-viz$ npm start 8080

> htm-school-viz@1.0.0 start /mnt/store/devel/HTM/htm_schools/htm-school-viz
> node index.js "8080"

htm-school-viz running on http://localhost:8080
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

The screen is stuck on a "loading" circle

**Comment by breznak** [comment]
This is on both Chromium, Firefox, Ununtu 16.04. 

Note: I get a warning `$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
` but I guess it's really just optional.

**Comment by rikkertkoppes** [comment]
Yeah, the npm error is likely unrelated

**Comment by rikkertkoppes** [comment]
It seems you have a few ports confused

- htm-school-viz runs on 8080 (or any other you provide by the command line)
- it expects nupic-history-server [to run on 8000](https://github.com/htm-community/htm-school-viz/blob/master/index.js#L13) which is NOT configurable
- nupic-history-server expects redis [to run on 6379](https://github.com/htm-community/nupic-history-server#installing), which is also NOT configurable

**Comment by breznak** [comment]
Please review the 2 PRs, @rikkertkoppes was right that I had the servers confused; but I think there still was an error with the ports. 

Now it's:
- redis (as default on 6379)
- nupic-history-server listens on 8080 (it actually listnes there, not configurable)
- htm-schools-viz expects "history" now correctly on 8080, and it itself runs on 8001 (now) 

Is this correct? :scream_cat:

**Comment by breznak** [comment]
I'd still be getting an error

```
(schools) mmm@mmm-U2442:/mnt/store/devel/HTM/htm_schools/nupic-history-server$ jobs
[1]+  Running                 redis-server &
(schools) mmm@mmm-U2442:/mnt/store/devel/HTM/htm_schools/nupic-history-server$ python webserver.py
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "webserver.py", line 404, in DELETE
    ioClient.nuke()
  File "/mnt/store/devel/HTM/htm_schools/nupic-history-server/nupic_history/io_client.py", line 154, in nuke
    for f in os.listdir(folder):
OSError: [Errno 2] No such file or directory: './working'

127.0.0.1:54632 - - [06/Apr/2017 16:58:50] "HTTP/1.1 DELETE /_flush/" - 500 Internal Server Error
```

...but I think it's a move in the right direction :thought_balloon:

**Comment by breznak** [comment]
And I was right :wink: 

Added a commit that fixes err above, now we face a new one: 

```
(schools) mmm@mmm-U2442:/mnt/store/devel/HTM/htm_schools/nupic-history-server$ python webserver.py
http://0.0.0.0:8080/
127.0.0.1:54852 - - [06/Apr/2017 17:13:52] "HTTP/1.1 DELETE /_flush/" - 200 OK
{u'boostStrength': 1,
 u'columnDimensions': [2048],
 u'dutyCyclePeriod': 1000,
 u'globalInhibition': True,
 u'inputDimensions': [631],
 u'localAreaDensity': 0,
 u'minPctOverlapDutyCycle': 0.001,
 u'numActiveColumnsPerInhArea': 40,
 u'potentialPct': 0.85,
 u'potentialRadius': 631,
 u'stimulusThreshold': 1,
 u'synPermActiveInc': 0.05,
 u'synPermConnected': 0.1,
 u'synPermInactiveDec': 0.008,
 u'wrapAround': True}
Traceback (most recent call last):
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 239, in process
    return self.handle()
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 462, in _delegate
    return handle_class(cls)
  File "/mnt/store/devel/HTM/htm_schools/schools/local/lib/python2.7/site-packages/web/application.py", line 438, in handle_class
    return tocall(*args)
  File "webserver.py", line 75, in POST
    sp = SpFacade(SP(**params), ioClient)
TypeError: __init__() got an unexpected keyword argument 'boostStrength'

127.0.0.1:54854 - - [06/Apr/2017 17:13:52] "HTTP/1.1 POST /_sp/" - 500 Internal Server Error
```

Which should be easy to fix. It's related to the recent renaming of the "boosting parameter", the decorator must match with the release used. 
@rhyolight can you please match and update the requirements to the latest release?

**Comment by rikkertkoppes** [comment]
No it's not correct

nupic-history-server should listen on 8000, start the server with `python webserver.py 8000` to specify that port

The docs may need some updating to reflect that. I can see it is confusing when you're not familiar with web.py. So in order:

- start redis (this should run as a service)
- start nupic-history server with `python webserver.py 8000`
- start htm-school-viz with `npm start 8080` (or any other port)

**Comment by breznak** [comment]
> nupic-history-server should listen on 8000, start the server with python webserver.py 8000 to specify that port 

Ok, that would also work, I did it the other way around: I let the history to run on :8080 and changed the visualizer to expect history running on 8080, so it really is correct now. ....We should decide what is a better approach, imho these PRs, as there are no parameters required and it runs out of the box (?) 

I'm facing the last problem with the facade: https://github.com/htm-community/htm-school-viz/issues/19#issuecomment-292207090 

PS: to validate this approach: you must review both the PRs linked here.

**Comment by rhyolight** [comment]
Thanks you guys!

**Comment by breznak** [comment]
@rhyolight do you have an idea about the last problem above, `TypeError: __init__() got an unexpected keyword argument 'boostStrength'` ?

I checked, and in SP it's called the same. So I don't know where this issue comes from: facade, capnp, web hooks,... ? 
The backtrace doesn't tell much to me, can you help us debugging, or point in some direction?

**Comment by rhyolight** [comment]
@breznak The only time I've ever seen this error is when I have an older version of NuPIC or nupic.core installed. You might check to see that there are no old versions installed in your environment.

**Comment by breznak** [comment]
Awesome, a good word comes a long way ;) I had the 0.5.7/0.4.13 older recommended versions installed, updated to the latest `v0.6.0` and it's running!! 

Btw, this is an awesome project, a sweet candy to play with :heart_eyes:
