### ISSUE TITLE
Help with 2D Topology

### ISSUE THREAD

**Issue by breznak** [htm-community/htm-school-viz#24]
@rhyolight Hello Matt, 

sorry for reaching for you this way, I couldn't get in touch on Gitter.. 
Could you please help me with 2D spatial pooler in C++? Similar as you've been using in the topology episodes here. 

Say I have input board 100x100, and SP 32x32, I want to select some input positions ({{99,0}, {0,0}, {0,99}}) and then let the SP compute. I know how to make a 2D SP: 
```
SpatialPooler sp{vector<int>{100, 100} /*input dims*/, vector<int>{32, 32} /*cols*/,...};
```
But I don't know how to format the input 1D vector for `compute()`, it should be a dense, binary 1d vector, but I don't know how the 2d is translated to 1d here. 
Thank you very much!

**Comment by rhyolight** [comment]
I think you still send it a 1d array, and because it knows the dimensions it will interpolate in with topology. For example, here is the raw data I sent to the SP to encode:
https://github.com/htm-community/htm-school-viz/blob/master/static/data/gifData/bird.json

**Comment by breznak** [comment]
Thank you very much Matt!! You are a life-saver :) 
My problem was how to "flatten" the data, and from the image you linked I was able to reconstruct it. So it seems that 
```
[a, b
c, d]
=> [a,b,c,d]
```

**Comment by breznak** [comment]
PS: the gitter seems dead? Where do you guys hang out now? 
https://gitter.im/numenta/public

**Comment by rhyolight** [comment]
I hang out on HTM Forum. That is the best place to get answers. I respond there quicker than anywhere else.
