### ISSUE TITLE
Running certain episodes fail with 404 error

### ISSUE THREAD

**Issue by listedegarde** [htm-community/htm-school-viz#30]
I have downloaded the numenta/nupic docker and installed nodeJS 8.x on it.  After running npm install and then npm start 8001, I can access the site at localhost:8001, but when I click on Episode 7 I never get past the loading GIF, and I get the error in the console:

`POST http://localhost:8001/_proxy/_sp/ 404 (Not Found)`

Some of the other episodes work fine, example: Episode 6.  The 404 error returned is returned by Nginx.

**Comment by listedegarde** [comment]
I found the problem.  This can be closed.  For anyone who stumbles upon this in the future, here is the solution: I was missing cell-viz and nupic-history-server.  Bascially the steps I used to solve it:

# Install Cell Viz
git clone https://github.com/htm-community/cell-viz
cd cell-viz
npm install .
npm run build

# Install Redis Server
apt install redis-server

# Install Nupic History Server
cd ..
git clone https://github.com/htm-community/nupic-history-server
cd nupic-history-server
pip install -r requirements.txt

# Upgrade numpy
pip install -U numpy

# Run servers:
redis-server &
python webserver.py &
cd ../htm-school-viz/
npm start 8001

**Comment by rhyolight** [comment]
Thanks for the note. I know it is complicated. I hope to simplify this in the future as I integrate these projects.
