### ISSUE TITLE
Can't get samples for episode 8 to load

### ISSUE THREAD

**Issue by mattroid** [htm-community/htm-school-viz#9]
I can get all the other samples to load and run just fine however. I've attached a screenshot that shows the console error message. Something about a _proxy call failing. 

<img width="1318" alt="screen shot 2016-10-04 at 11 20 39 am" src="https://cloud.githubusercontent.com/assets/249426/19086860/bde0a778-8a24-11e6-9737-de521dc4feb6.png">

**Comment by rhyolight** [comment]
You need to run nupic-history-server for the SP and TM demos to work. Re-read the README. 😉  https://github.com/htm-community/htm-school-viz#run
